@startuml(id=SampleLibrary)
interface SampleLibrary{
+invokeLayer(): Playable
}
@enduml


@startuml(id=V1SampleLibrary)
class V1SampleLibrary<<SampleLibrary>>{

}
@enduml


@startuml(id=SampleLibraryFactory)
class SampleLibraryFactory{
+prepareSamples(): SampleLibrary
}
@enduml


@startuml(id=TriggerGraph)
interface TriggerGraph{
+invokeLayer(): Playable
+addLayer(TiggerLayer)
}
@enduml

@startuml(id=V1TriggerGraph)
class V1TriggerGraph<<TriggerGraph>>{

}
@enduml

@startuml(id=TriggerGraphFactory)
class TriggerGraphFactory{
+{static}prepareTriggers(): TriggerGraph
}
@enduml


'''



@startuml(id=Instrument)
class Instrument{
-Player
init()
}
@enduml


@startuml(id=ResourceManager)
class ResourceManager{

+{static} prepareSnapshot()
-{static}  analyzeFiles()
+{static} getGroupCount()
+{static} getLayerCount(group: Int)
+{static} getRoundRobinCount(group: Int, layer: Int)
+{static} getResource(group: Int, layer: Int, roundRobin: Int)
}
@enduml



@startuml(id=TriggerManager)
interface TriggerManager{
prepareTriggerManager()
computeZoneLayer(Point): ZoneLayer
}
@enduml


@startuml(id=SimpleTriggerManager)
class SimpleTriggerManager<<TriggerManager>>{
TriggerGraph
}
@enduml



@startuml(id=TriggerZone)
interface TriggerZone{
invokeLayer(Point): ZoneLayer
}
@enduml


@startuml(id=V1TriggerZone)
class V1TriggerZone<<TriggerZone>>{

}
@enduml





@startuml(id=ZoneLayer)
interface ZoneLayer{
isMatch(Point): boolean
}
@enduml


@startuml(id=V1ZoneLayer)
class V1ZoneLayer<<ZoneLayer>>{
topLimit: Int
bottomLimit: Int
rightLimit: Int
leftLimit: Int

}
@enduml



@startuml(id=PlayerFactory)
class PlayerFactory{

+{static} getInstance(TriggerManager, SampleManager)
}
@enduml


@startuml(id=Player)
interface Player{
+invokePlayable(): Playable
-startThread()
-play(Playable)
}
@enduml



@startuml(id=SimplePlayer)
class SimplePlayer<<Player>>{
-TriggerManager
-SampleManager
}
@enduml



@startuml(id=LayerLogic)
interface LayerLogic{
computeID(): SampleID
addInstance(SampleID)
}
@enduml


@startuml(id=SimpleLayerLogic)
class SimpleLayerLogic<<LayerLogic>>{
history: Queue<SampleID>

}
@enduml


@startuml(id=SampleManager)
interface SampleManager{
+computeSample(ZoneLayer): Playable
+invokeSampleGroup(ZoneLayer): Playable
+prepareSampleManager()
}
@enduml


@startuml(id=SimpleSampleManager)
class SimpleSampleManager<<SampleManager>>{
-layers: Map<ZoneLayer, SampleLayer>
}
@enduml


@startuml(id=SampleGroup)
interface SampleGroup{
invokeLayer(): Playable
}
@enduml


@startuml(id=V1SampleGroup)
class V1SampleGroup<<SampleGroup>>{
-Map<ZoneLayer, SampleLayer>
}
@enduml

@startuml(id=SampleLayer)
interface SampleLayer{
+invokeSample(): Playable
+addSample(Playable)
}
@enduml


@startuml(id=V1SampleLayer)
class V1SampleLayer<<SampleLayer>>{
samplesThisLayer: Map<SampleID, Playable>
}
@enduml



@startuml(id=SampleID)
interface SampleID{
identify()
}
@enduml


@startuml(id=SampleCoords)
class SampleCoords<<SampleID>>{
layer: Int
roundRobin: Int
}
@enduml


@startuml(id=Playable)
interface Playable{
-createPlayer()
+play()
+getSampleID(): SampleID
}
@enduml


@startuml(id=V1Sample)
class V1Sample<<Playable>>{
context: Context
sampleID: SampleID
resourceID: Int
{field} availPlayers: Queue<MediaPlayer> (or ExoPlayer)
{field} busyPlayers: Queue<MediaPlayer> (or ExoPlayer)
moveToBusy()
}
@enduml

