@startuml

!include Declarations.puml!ResourceManagerFactory
!include Declarations.puml!SampleLibrary
!include Declarations.puml!ZoneGraph
!include Declarations.puml!V1SampleLibrary
!include Declarations.puml!V1ZoneGraph
!include Declarations.puml!Instrument
!include Declarations.puml!ResourceManagerFactory
!include Declarations.puml!ResourceManager
!include Declarations.puml!ZoneFactory
!include Declarations.puml!ZoneManager
!include Declarations.puml!SimpleZoneManager
!include Declarations.puml!SampleFactory
!include Declarations.puml!ZoneManager
!include Declarations.puml!ArticulationZone
!include Declarations.puml!V1ArticulationZone
!include Declarations.puml!VelocityZone
!include Declarations.puml!V1VelocityZone
!include Declarations.puml!Player
!include Declarations.puml!SimplePlayer
!include Declarations.puml!PlayerFactory
!include Declarations.puml!RoundRobinLogic
!include Declarations.puml!SimpleRoundRobinLogic
!include Declarations.puml!SampleManager
!include Declarations.puml!SimpleSampleManager
!include Declarations.puml!Articulation
!include Declarations.puml!V1Articulation
!include Declarations.puml!VelocityLayer
!include Declarations.puml!V1VelocityLayer
!include Declarations.puml!SampleID
!include Declarations.puml!SampleCoords
!include Declarations.puml!Sample
!include Declarations.puml!V1Sample

Player <|.. SimplePlayer
ZoneManager <|.. SimpleZoneManager
SampleManager <|.. SimpleSampleManager
ZoneGraph <|.. V1ZoneGraph
ArticulationZone <|.. V1ArticulationZone
Articulation <|.. V1Articulation
SampleLibrary <|.. V1SampleLibrary
VelocityLayer <|.. V1VelocityLayer
VelocityZone <|.. V1VelocityZone
RoundRobinLogic <|.. SimpleRoundRobinLogic
Sample <|.. V1Sample
SampleID <|.. SampleCoords


Instrument *-- ResourceManager
Instrument *-- Player

SimplePlayer *- ZoneManager
SampleManager -* SimplePlayer

Instrument .> SampleFactory
ZoneFactory <. Instrument
PlayerFactory <.. Instrument

V1ArticulationZone o-- VelocityZone
V1Sample *- SampleID
V1Articulation o-- VelocityLayer

SimpleZoneManager *-  ZoneGraph
V1ZoneGraph o-- ArticulationZone
SampleLibrary -* SimpleSampleManager
V1SampleLibrary o-- Articulation

V1VelocityLayer o-- SampleID
V1VelocityLayer o-- Sample
SimpleRoundRobinLogic o-- SampleID
hide members
@enduml