@startuml
!include Declarations.puml!ResourceManager
!include Declarations.puml!TriggerGraphFactory
!include Declarations.puml!TriggerManager
!include Declarations.puml!SampleLibraryFactory
!include Declarations.puml!TriggerManager
!include Declarations.puml!TriggerZone
!include Declarations.puml!HeadZone
!include Declarations.puml!RimZone
!include Declarations.puml!ZoneLayer
!include Declarations.puml!HeadZoneLayer
!include Declarations.puml!RimZoneLayer
!include Declarations.puml!Player
!include Declarations.puml!LayerLogic
!include Declarations.puml!SampleManager
!include Declarations.puml!SampleGroup
!include Declarations.puml!HeadSampleGroup
!include Declarations.puml!RimSampleGroup
!include Declarations.puml!SampleLayer
!include Declarations.puml!SampleID
!include Declarations.puml!Playable

@enduml