@startuml
package instrument{
!include Declarations.puml!Player
!include Declarations.puml!SimplePlayer
!include Declarations.puml!PlayerFactory
!include Declarations.puml!Instrument
!include Declarations.puml!ResourceManagerFactory
!include Declarations.puml!ResourceManager
!include Declarations.puml!SimpleResourceManager
}

package trigger{
!include Declarations.puml!TriggerGraphFactory
!include Declarations.puml!TriggerManager
!include Declarations.puml!SimpleTriggerManager
!include Declarations.puml!TriggerManager
package triggergraph{
!include Declarations.puml!TriggerGraph
!include Declarations.puml!V1TriggerGraph
package triggerzone{
!include Declarations.puml!TriggerZone
!include Declarations.puml!HeadZone
!include Declarations.puml!RimZone
package zonelayer{
!include Declarations.puml!ZoneLayer
!include Declarations.puml!HeadZoneLayer
!include Declarations.puml!RimZoneLayer
}
}
}
}




package sample{
!include Declarations.puml!SampleLibraryFactory
!include Declarations.puml!SampleManager
!include Declarations.puml!SimpleSampleManager
package samplelibrary{
!include Declarations.puml!SampleLibrary
!include Declarations.puml!V1SampleLibrary
package samplegroup{
!include Declarations.puml!SampleGroup
!include Declarations.puml!HeadSampleGroup
!include Declarations.puml!RimSampleGroup
package samplelayer{
!include Declarations.puml!SampleLayer
!include Declarations.puml!HeadSampleLayer
!include Declarations.puml!RimSampleLayer
!include Declarations.puml!LayerLogic
!include Declarations.puml!SimpleLayerLogic
package playable{
!include Declarations.puml!SampleID
!include Declarations.puml!SampleCoords
!include Declarations.puml!Playable
!include Declarations.puml!SimpleSample

}
}
}
}
}
@enduml
