@startuml
-->Instrument: onTouch()


Instrument->Player++: play(Point)
Player->TriggerManager++: computeZoneLayer(Point)
return ZoneLayer


Player->SampleManager++: computeSample(ZoneLayer)
SampleManager->SampleLibrary++: invokeLayer(ZoneLayer)
SampleLibrary->SampleGroup++: invokeLayer(ZoneLayer)
SampleGroup->SampleLayer++: invokeSample()
SampleLayer->LayerLogic++:computeID(SampleLayer)
LayerLogic->LayerLogic++:addInstance()
deactivate
return SampleCoords
SampleLayer->Playable++:getPlayable(SampleCoords)
Playable->Playable:moveToBusy()


return Playable
return Playable
return Playable
return Playable
return Playable

Player->Player++:startThread()

Player->Playable++: play()
return
deactivate
return done
@enduml