@startuml
-->Instrument: onTouch()

Instrument->Player++: play(Point)
Player->ZoneManager++: computeVelocityZone(Point)
ZoneManager->ZoneGraph++: invokeZone(Point)
ZoneGraph->ArticulationZone++: invokeZone(Point)
ArticulationZone->VelocityZone++: getLayer(Point)
return VelocityZone
return VelocityZone
return VelocityZone
return VelocityZone
Player->: computeSample()
@enduml