@startuml
!include Declarations.puml!Instrument
!include Declarations.puml!Player
!include Declarations.puml!SampleManager
!include Declarations.puml!ZoneManager
!include Declarations.puml!Sample
!include Declarations.puml!VelocityLayer
!include Declarations.puml!ArticulationZone
!include Declarations.puml!V1VelocityLayer
!include Declarations.puml!VelocityZone
!include Declarations.puml!V1VelocityZone
!include Declarations.puml!Articulation
!include Declarations.puml!RoundRobinLogic
!include Declarations.puml!ZoneGraph
!include Declarations.puml!SampleLibrary

Instrument .> Player
Player ..> SampleManager
Player ..> ZoneManager
Player ..> Sample: weak

SampleManager ..> SampleFactory
SampleFactory ..> Articulation
Articulation ..> VelocityLayer
VelocityLayer ..> RoundRobinLogic
VelocityLayer ..> Sample

ZoneManager ..> ZoneGraph
ZoneGraph ..> ArticulationZone
ArticulationZone ..> VelocityLayer

@enduml