@startuml
-->Instrument: onTouch()


Instrument->Player++: play(Point)
Player->TriggerManager++: computeZoneLayer(Point)
return ZoneLayer


Player->SampleManager++: computeSample(ZoneLayer)
SampleManager->SampleLibrary++: invokeLayer(ZoneLayer)
SampleLibrary->SampleGroup++: invokeLayer(ZoneLayer)
SampleGroup->SampleLayer++: invokeSample()
SampleLayer->LayerLogic++:computeID()
LayerLogic->LayerLogic++:addInstance()
deactivate
return SampleID
SampleLayer->Playable++:getPlayable(SampleID)
Playable->Playable:moveToBusy()


return Playable
return Playable
return Playable
return Playable
return Playable

Player->Player++:startThread()

Player->Playable++: play()
return
Player->Playable++: finish()
Playable->Playable: moveToAvail()
return done
deactivate
return done
@enduml