@startuml
Instrument->Instrument++: init()

Instrument->ResourceManager++: ResourceManager()
ResourceManager->: analyzeFiles()
ResourceManager<--
return ResourceManager
Instrument->: prepareSamples()
Instrument<--:SampleFactory


Instrument->SampleManager: SampleManager(SampleFactory)


Instrument->ZoneFactory++: ZoneFactory()
ZoneFactory->ZoneFactory++: prepareZones()
ZoneFactory->ResourceManager++: getArticulationCount()
return Int


loop forEachArticulationInSnapshot
ZoneFactory->ArticulationZone++: ArticulationZone()
return new
ZoneFactory->ResourceManager++: getLayerCount(articulationNumber: Int)
return Int
loop forEachLayerInArticulation
ZoneFactory->VelocityZone++: VelocityZone()
return new


ZoneFactory->ArticulationZone++:addLayer(VelocityZone)
return
end loop
ZoneFactory->ZoneFactory++: addZone(ArticulationZone)
deactivate
end loop
deactivate
return ZoneGraph


Instrument->ZoneManager++: ZoneManager(ZoneGraph)
return ZoneManager

Instrument->ZoneManager++: SampleManager(SampleLibrary)
return SampleManager


Instrument->PlayerFactory++: getInstance(ZoneManager, SampleManager)
return PlayerFactory
@enduml