@startuml
Instrument->Instrument++: init()

Instrument->ResourceManager++: prepareSnapshot()
ResourceManager->: analyzeFiles()
ResourceManager<--

return
Instrument-> SampleFactory++: prepareSamples()
SampleFactory->ResourceManager++: getGroupCount()
return Int

loop forEachGroupInSnapshot
SampleFactory->Articulation++: Articulation()
return new
SampleFactory->ResourceManager++: getLayerCount(group: Int)
return Int
loop forEachLayerInGroup
SampleFactory->VelocityLayer++: VelocityLayer(layerNumber, RoundRobinLogic)
return new
SampleFactory->ResourceManager++: getRoundRobinCount(group: Int, layer: Int)
return Int
loop forEachSampleInLayer
SampleFactory->Sample++: Sample(SampleCoords, FileSnapshot)
Sample->Sample++: init()

deactivate
return new
SampleFactory->VelocityLayer++: addSample(Sample)
return
end loop
SampleFactory->Articulation++:addLayer(VelocityLayer)
return
end loop
SampleFactory->SampleFactory++: addGroup(Articulation)
deactivate
end loop

return SampleLibrary

@enduml