@startuml
header This diagram shows dependencies that are implied by the prepare sequence only, and doesn't not pretend to be an exhaustive study of for these types dependencies.

!include Declarations.puml!Instrument
!include Declarations.puml!Player
!include Declarations.puml!ResourceManager
!include Declarations.puml!ZoneFactory
!include Declarations.puml!SampleFactory
!include Declarations.puml!ZoneManager
!include Declarations.puml!SampleManager
!include Declarations.puml!Articulation
!include Declarations.puml!VelocityLayer
!include Declarations.puml!ArticulationZone
!include Declarations.puml!VelocityLayer
!include Declarations.puml!Sample

folder externalResources{
}


Instrument ..> Player
Instrument ..> ResourceManager
Instrument ..> SampleFactory
Instrument ..> ZoneFactory
Instrument ..> ZoneManager
Instrument ..> SampleManager

externalResources <. ResourceManager

SampleFactory ..> ResourceManager
SampleFactory ..> Articulation
SampleFactory ..> VelocityLayer
SampleFactory ..> Sample
Sample ..> ResourceManager

ZoneFactory ..> ResourceManager
ZoneFactory ..> ArticulationZone
ZoneFactory ..> VelocityLayer

@enduml