@startuml
Instrument->Instrument++: init()

Instrument->ResourceManager++: analyzeFiles()
ResourceManager->: analyzeFiles()
ResourceManager<--

return
Instrument-> SampleFactory++: prepareSamples()
SampleFactory->ResourceManager++: getArticulationCount()
return Int

loop forEachArticulationInSnapshots
SampleFactory->Articulation++: Articulation()
return new
SampleFactory->ResourceManager++: getLayerCount(articulationNumber: Int)
return Int
loop forEachLayerInArticulation
SampleFactory->VelocityLayer++: VelocityLayer(layerNumber, RoundRobinLogic)
return new
SampleFactory->ResourceManager++: getRoundRobinCount(articulationNumber: Int, layer: Int)
return Int
loop forEachSampleInLayer
SampleFactory->Sample++: Sample(SampleCoords, FileSnapshots)
Sample->Sample++: init()

deactivate
return new
SampleFactory->VelocityLayer++: addSample(Sample)
return
end loop
SampleFactory->Articulation++:addLayer(VelocityLayer)
return
end loop
SampleFactory->SampleFactory++: addArticulation(Articulation)
deactivate
end loop

return SampleLibrary

@enduml